### ISSUE TITLE
не компилится

### ISSUE THREAD

**Issue by suprimex** [IoTManagerProject/IoTManager#83]
Свежая инсталяция, при попытке скомпилить получаю ошибку:
more than one instance of overloaded function "analogWrite" matches the argument list: 

-- function "analogWrite(uint8_t APin, uint16_t AValue)" 
(declared at line 9 of "P:\Compilation\IoTManager\.pio\libdeps\esp32_4mb\ESP32Servo\src\analogWrite.h") 

-- function "analogWrite(uint8_t pin, uint32_t value, uint32_t valueMax = 255U)" 
(declared at line 21 of "P:\Compilation\IoTManager\.pio\libdeps\esp32_4mb\ESP32 AnalogWrite\src\analogWrite.h") 

-- argument types are: (unsigned int, long)

из лога:
 .....
Compiling .pio\build\esp32_4mb\src\items\vSensorCcs811.cpp.o
src/items/vPwmOut.cpp: In member function 'void PwmOut::execute(String)':
src/items/vPwmOut.cpp:23:36: error: call of overloaded 'analogWrite(unsigned int&, long int)' is ambiguous
     analogWrite(_pin, state.toInt());
                                    ^
In file included from .pio/libdeps/esp32_4mb/ESP32Servo/src/ESP32Servo.h:67:0,
                 from include/ESP32.h:12,
                 from include/Global.h:14,
                 from include/items/vPwmOut.h:5,
                 from src/items/vPwmOut.cpp:3:
.pio/libdeps/esp32_4mb/ESP32Servo/src/analogWrite.h:9:8: note: candidate: void analogWrite(uint8_t, uint16_t)
   void analogWrite( uint8_t APin, uint16_t AValue );
        ^
In file included from include/ESP32.h:18:0,
                 from include/Global.h:14,
                 from include/items/vPwmOut.h:5,
                 from src/items/vPwmOut.cpp:3:
.pio/libdeps/esp32_4mb/ESP32 AnalogWrite/src/analogWrite.h:21:6: note: candidate: void analogWrite(uint8_t, uint32_t, uint32_t)
 void analogWrite(uint8_t pin, uint32_t value, uint32_t valueMax = 255);
      ^
*** [.pio\build\esp32_4mb\src\items\vPwmOut.cpp.o] Error 1
=================================================== [FAILED] Took 14.12 seconds ===================================================

**Comment by IoTManagerProject** [comment]
Используйте пока что ветку beta. Там последняя версия.

**Comment by IoTManagerProject** [comment]
исправил
